#!/usr/bin/env bash
# Verified, argument-free push path for local agents.
set -euo pipefail

EXPECTED_REPO="petralabx/local-inference"
WRAPPER_PATH="scripts/push-agent-branch.sh"

if [[ $# -ne 0 ]]; then
  printf 'usage: %s\n' "$(basename "$0")" >&2
  exit 2
fi

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

is_expected_remote() {
  local url="$1"
  [[ "$url" =~ ^https://([^/@]+@)?github\.com/petralabx/local-inference(\.git)?$ ||
    "$url" =~ ^git@github\.com:petralabx/local-inference(\.git)?$ ||
    "$url" =~ ^ssh://git@github\.com/petralabx/local-inference(\.git)?$ ]]
}

ORIGIN_URL="$(git remote get-url origin)"
if ! is_expected_remote "$ORIGIN_URL"; then
  printf 'refusing push: origin fetch URL must target %s\n' "$EXPECTED_REPO" >&2
  exit 1
fi

mapfile -t PUSH_URLS < <(git remote get-url --push --all origin)
if [[ ${#PUSH_URLS[@]} -ne 1 ]] || ! is_expected_remote "${PUSH_URLS[0]}"; then
  printf 'refusing push: origin must have exactly one canonical push URL\n' >&2
  exit 1
fi

BRANCH="$(git branch --show-current)"
if [[ ! "$BRANCH" == cursor/* ]]; then
  printf 'refusing push: branch must match cursor/*\n' >&2
  exit 1
fi

if [[ -n "$(git status --porcelain)" ]]; then
  printf 'refusing push: commit or remove working-tree changes first\n' >&2
  exit 1
fi

if ! git cat-file -e "origin/main:$WRAPPER_PATH" ||
  ! git diff --quiet origin/main -- "$WRAPPER_PATH"; then
  printf 'refusing push: wrapper must match origin/main; fetch main and do not edit this file\n' >&2
  exit 1
fi

resolve_python() {
  local candidate
  if [[ -n "${PYTHON_BIN:-}" ]]; then
    if [[ -x "$PYTHON_BIN" ]] || command -v "$PYTHON_BIN" >/dev/null 2>&1; then
      printf '%s\n' "$PYTHON_BIN"
      return 0
    fi
    return 1
  fi
  for candidate in \
    "$REPO_ROOT/.venv/Scripts/python.exe" \
    "$REPO_ROOT/.venv/bin/python" \
    python3 \
    python; do
    if [[ -x "$candidate" ]] || command -v "$candidate" >/dev/null 2>&1; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done
  return 1
}

PYTHON_CMD="$(resolve_python)" || {
  printf 'refusing push: Python 3 is required for repository validation\n' >&2
  exit 1
}
"$PYTHON_CMD" -m unittest discover -s tests -v
"$PYTHON_CMD" scripts/check-brand-repo-structure.py
git push -u origin "$BRANCH"
